test:
  workers:
    number: 100
  rounds:
    - label: test
      txDuration: 30
      rateControl:
        type: fixed-rate
        opts:
          tps: 1500
      workload:
        module: workload/readAssetNew.js
        arguments:
          assets: 4000
          contractID: IoT-cc
monitors:
  resource:
    - module: docker
      options:
        interval: 5
        cpuUsageNormalization: true
        containers:
          - /peer0.org1.example.com
          - /peer0.org2.example.com
          - /peer0.org3.example.com
          - /orderer.example.com
